version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_Edtrack_visitor
    ports:
      - "0840:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
      - phpmyadmin
    networks:
      - laravel

  mysql:
    image: mysql:8.0.32
    container_name: mysql_Edtrack_visitor
    restart: unless-stopped
    tty: true
    ports:
      - "0830:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: Edtrack_visitor
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_Edtrack_visitor
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_Edtrack_visitor
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "0820:9000"
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer_Edtrack_visitor
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan_Edtrack_visitor
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
  
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_Edtrack_visitor
    restart: always
    ports:
      - 0850:80
    environment:
      PMA_HOST: mysql_Edtrack_visitor
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  npm:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: npm_Edtrack_visitor
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel
    entrypoint: ['npm', 'run', 'dev']